
#ifndef QPARAMETERWIDGET_EXPORT_H
#define QPARAMETERWIDGET_EXPORT_H

#ifdef QPARAMETERWIDGET_STATIC_DEFINE
#  define QPARAMETERWIDGET_EXPORT
#  define QPARAMETERWIDGET_NO_EXPORT
#else
#  ifndef QPARAMETERWIDGET_EXPORT
#    ifdef QParameterWidget_EXPORTS
        /* We are building this library */
#      define QPARAMETERWIDGET_EXPORT 
#    else
        /* We are using this library */
#      define QPARAMETERWIDGET_EXPORT 
#    endif
#  endif

#  ifndef QPARAMETERWIDGET_NO_EXPORT
#    define QPARAMETERWIDGET_NO_EXPORT 
#  endif
#endif

#ifndef QPARAMETERWIDGET_DEPRECATED
#  define QPARAMETERWIDGET_DEPRECATED __declspec(deprecated)
#endif

#ifndef QPARAMETERWIDGET_DEPRECATED_EXPORT
#  define QPARAMETERWIDGET_DEPRECATED_EXPORT QPARAMETERWIDGET_EXPORT QPARAMETERWIDGET_DEPRECATED
#endif

#ifndef QPARAMETERWIDGET_DEPRECATED_NO_EXPORT
#  define QPARAMETERWIDGET_DEPRECATED_NO_EXPORT QPARAMETERWIDGET_NO_EXPORT QPARAMETERWIDGET_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef QPARAMETERWIDGET_NO_DEPRECATED
#    define QPARAMETERWIDGET_NO_DEPRECATED
#  endif
#endif

#endif /* QPARAMETERWIDGET_EXPORT_H */
